### ISSUE TITLE
Question: Does kicad has something like area rules to reuse layout of submodules?

### ISSUE THREAD

**Issue by konosubakonoakua** [El-Luhb/nvme-Carrier-for-LattePanda-Mu#10]
just a wonder, because I have used this functionality in Altium.
Have you use same functionality in kicad? thank your answer in advance😊

**Comment by El-Luhb** [comment]
Yes, there are some options for this. But I didn't use them. The reason for this was simply that I didn't have the time to find out how it works. For me, it was enough to just copy and paste.

**Comment by konosubakonoakua** [comment]
Thank you.
